/* eslint-disable @typescript-eslint/no-explicit-any */

import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Link from "next/link";


export const metadata: Metadata = {
    title: "This is home page",
    description: "Generated by create next app",
};


const HomePage = async () => {

    const res = await fetch("https://abc.madrasatuahmad.com/api/courses", {
        cache: "no-cache"
    })

    const data = await res.json();

    const courses = data.data.data





    return (
        <div className=" max-w-4xl mx-auto">

            {courses.map((course: any) => (
                <div key={course.id}>
                    <h1 className=" text-2xl "> ({course.id}) {course.title} </h1>
                    <Button asChild>
                        <Link href={`/${course.id}`}>
                            Read more
                        </Link>
                    </Button>

                </div>

            ))}


        </div>
    );
};

export default HomePage;